以3层神经网络为对象，输入层（第0层）有2个神经元，隐藏层（第1层）有3个神经元，隐藏层（第2层）有2个神经元，输出层（第3层）有2个神经元。
实现从输入到输出的前向处理。

    第0层输入神经元：x1,x2
    第1层隐藏层神经元：a1,a2,a3
    第2层隐藏层神经元：b1,b2
    第3层输出层神经元：y1，y2

从输入层到第1层的信号传递
a1=x1*w11+x2*w21+b1   #偏置权重b中的元素数量取决于后一层神经元的数量

In [2]:
import numpy as np
X=np.array([1.0,0.5])
W1=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1=np.array([0.1,0.2,0.3])
print(W1.shape)
print(X.shape)
print(B1.shape)
A1=np.dot(X,W1)+B1


(2, 3)
(2,)
(3,)


以上计算出了隐藏层第1层的加权和（加权信号和偏置的总和）用A表示，加下来计算其被激活函数转换后，用Z表示

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

Z1=sigmoid(A1)
print(A1)
print(Z1)


[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


第一层到第二层的信号传递：
第一层的输出Z1 变成第二层的输入

In [7]:
W2=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2=np.array([0.1,0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)
A2=np.dot(Z1,W2)+B2
Z2=sigmoid(A2)
print(A2)
print(Z2)   



(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


最后是第二层到输出层的信号传递，最后的激活函数和之前的隐藏层有所不同。
#输出层的激活函数用恒等函数 ，恒等函数会将输入按原样输出
输出层所用的激活函数，要根据求解问题的性质决定。一般回归问题用恒等函数，二元分类问题用sigmoid函数，多元分类问题用softmax函数


In [8]:
def identity_function(x):   #恒等函数
    return x    

W3=np.array([[0.1,0.3],[0.2,0.4]])
B3=np.array([0.1,0.2])

A3=np.dot(Z2,W3)+B3
Y=identity_function(A3)
print(Y)


[0.31682708 0.69627909]


In [9]:
#全部3层网络的实现代码
def init_network():
    network={}
    network['W1']=np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1']=np.array([0.1,0.2,0.3])
    network['W2']=np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2']=np.array([0.1,0.2])
    network['W3']=np.array([[0.1,0.3],[0.2,0.4]])
    network['b3']=np.array([0.1,0.2])
    return network

def forward(network,x):
    W1,W2,W3=network['W1'],network['W2'],network['W3']
    b1,b2,b3=network['b1'],network['b2'],network['b3']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    a3=np.dot(z2,W3)+b3
    y=identity_function(a3)
    return y
network=init_network()
x=np.array([1.0,0.5])     #输入层
y=forward(network,x)      #输出层
print(y)

[0.31682708 0.69627909]


softmax函数：
$$
y_k = \frac{exp(a_k)}{\sum_{i=1}^nexp(a_i)}
$$


输出层的设计：神经网络可以用在分类问题和回归问题上，需要根据情况改变输出层的激活函数
     
     分类问题：输出层的神经元数为分类数，激活函数为softmax函数。（比如区分图像是男性还是女性）
     回归问题：输出层的神经元数为1，激活函数为恒等函数。（比如根据一个人的图像预测这个人的体重，类似“54.5kg”这样的预测）

    输出层的激活函数：
        回归问题：恒等函数，对于输入信息，不加任何改动的直接输出
        分类问题：softmax函数  
        （softmax函数的输出是0.0到1.0之间的实数，并且所有输出值的和为1。）
        神经网络的输出是0.7的话，这表示“70%的概率是这个图像是男性，30%的概率是这个图像是女性”。
        softmax函数式：
            yk = exp(ak) / Σexp(ai)
            exp(x)表示e的x次方，假设输出层共有n个输出，计算第k个神经元的输出为yk,
            那么softmax函数的表达式为：
            y1 = exp(a1) / (exp(a1) + exp(a2) + ... + exp(an))
            y2 = exp(a2) / (exp(a1) + exp(a2) + ... + exp(an))
            ...
            yn = exp(an) / (exp(a1) + exp(a2) + ... + exp(an))
            其中，yk是第k个输出，ak是神经网络的第k个输出，i是和号的下标，表示对所有的输出求和。



In [10]:
import numpy as np
a=np.array([0.3,2.9,4.0])
exp_a=np.exp(a)
print(exp_a)
sum_exp_a=np.sum(exp_a)
print(sum_exp_a)
y=exp_a/sum_exp_a
print(y)
print(np.sum(y))    



[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]
1.0


In [11]:
#定义softmax函数
def softmax(a):
    exp_a=np.exp(a)
    sum_exp_a=np.sum(exp_a)
    y=exp_a/sum_exp_a
    return y

实现softmax函数时的注意事项：
计算时需要注意溢出问题，softmax函数的实现中要实现函数的指数运算，此时指数函数的值很容易变得很大，即输入值过大或过小导致指数函数的计算结果超出表示范围。
为了防止溢出，一般会在计算指数函数之前，先将输入值减去最大值，这样最大值就变成了0，其他值就都变成了负数。

比如e的10次方会超过20000，e的100次方会变成后面有40多个0的超大值，e的1000次方会返回一个表示无穷大的inf，计算机在处理数时，数值必须在4字节或者8字节的有限宽度内。这意味着数存在有效位数，也就是说可以表示数值的范围是有限的。

In [23]:
import numpy as np
a=np.array([1010,1000,990])
#np.exp(a)/np.sum(np.exp(a))   #[nan,nan,nan]
c=np.max(a)
a-c
np.exp(a-c)/np.sum(np.exp(a-c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [ ]:
def softmax(a):
    c=np.max(a)
    exp_a=np.exp(a-c)
    sum_exp_a=np.sum(exp_a)
    y=exp_a/sum_exp_a
    return y
    

softmax 函数的特征：
1、softmax 函数的输出是0到1之间的实数。
2、softmax 函数的输出值之和为1。
3、softmax 函数的输出值可以解释为概率。

输出层神经元的数量：
输出层神经元的数量需要根据待解决的问题来确定。
如果是分类问题，输出层神经元的数量需要等于分类的类别数。
如果是回归问题，输出层神经元的数量需要等于待预测的数值的数量。