多维数组就是“数字的集合”，数字排成一列的集合、排成长方形的集合、排成三维状或者（更加一般化的）N维状的集合都称为多维数组。下面我们就用NumPy来生成多维数组，先从前面介绍过的一维数组开始。

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.shape) # 数组的形状 
print(a.size) # 数组的元素个数,这里的A.shape的结果是个元组(tuple)。这是因为一维数组的情况下也要返回和多维数组的情况下一致的结果
print(a.itemsize) # 数组中每个元素的字节大小
print(a.dtype)  # 数组元素的类型
print(a.ndim) # 数组的维数

[1 2 3]
(3,)
3
8
int64
1


二维数组：二维数组也称为矩阵(matrix)

In [ ]:
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape) # 表示第一个维度有2个元素，第二个维度有3个元素，另外，第一个维度对应第0维，第二个维度对应第1维（Python的索引从0开始）
print(b.size)
print(b.itemsize)
print(b.dtype)
print(b.ndim)


[[1 2 3]
 [4 5 6]]
(2, 3)
6
8
int64
2


In [10]:
#矩阵乘法
import numpy as np
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[5,6],[7,8],[9,10]])
print(a)
print(b)
print(a.dot(b)) # 矩阵乘法
print (np.dot(a,b)) # 矩阵乘法


[[1 2 3]
 [3 4 5]]
[[ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 46  52]
 [ 88 100]]
[[ 46  52]
 [ 88 100]]
